apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: registry.access.redhat.com/ubi8/ubi
  namespace: datamesh
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/ubi:8.7-1037
      name: 8.7-1037
